services:

    app.map_manager:
        class: AppBundle\Manager\MapManager
        arguments:
            - @doctrine.orm.entity_manager

    app.archetype_manager:
        class: AppBundle\Manager\ArchetypeManager
        arguments:
            - @doctrine.orm.entity_manager
